@startuml RealizaciónCu07VistaDinámica
' CU 07 Crear Proyecto
skinparam roundcorner 20
skinparam maxmessagesize 60
autonumber
Actor ":__Usuario__" as U
create boundary "__:PantallaRegistrarProyecto__" as PRP
U --> PRP : opcionCrearNuevoProyecto()
PRP -> PRP : abrirVentana()
create control "__:GestorRegistrarProyecto__" as GRP
PRP --> GRP : newRegistrarProyecto()
GRP -> PRP : solicitarIngresoDeDatos()
U -> PRP : tomarIngresoNombre()
U -> PRP : tomarIngresoDescripción()
U -> PRP : tomarSelecciónRequiereRevisión()
U -> PRP : tomarOpciónCrearProyecto()
PRP -> GRP : tomarSelecciónCrearProyecto()
GRP -> GRP : verificarDatosMínimos()
entity "__Actual:Sesión__" as ASS
GRP -> ASS : getUsuarioLogueado()
GRP -> GRP: obtenerRolOwner()
entity "__Rol__" as R
GRP -> R: *sosOwner()
GRP -> GRP : crearProyecto()
create entity "__Nuevo:Proyecto__" as NP

GRP --> NP : new()
NP -> NP: crearNuevoRolEnProyecto()
entity "RolEnProyecto" as ReP
NP --> ReP: new()
GRP -> GRP : finCU()
@enduml

@startuml RealizaciónCu07VistaEstática
left to right direction
hide <<Entity>> circle
hide <<Boundary>> circle
hide <<Control>> circle
class Usuario<<Entity>>{
    - email
    - nombreUsuario
    - contraseña
    + 10. esTuEmail()
}

class Proyecto<<Entity>>{
    - nombre
    - descripcion
    - tareas: Tarea
    + 15. new()
    + 16. crearNuevoRolEnProyecto()
}

class GestorCrearProyecto<<Control>> {
    - nombreUsuario
    - descripciónUsuario
    - listaColaboradores
    + 3. newRegistrarTarea()
    + 9. tomarSelecciónCrearProyecto()
    + 10. verificarDatosMinimos()
    + 12. obtenerRolOwner()
    + 14. crearProyecto()
    + 18. finCU()
}

class Rol<<Entity>>{
    - nombre
    - descripcion
    - ambito
    + 13. sosOwner()

}
class RolEnProyecto<<Entity>>{ 
    +17. new()
}

class PantallaCrearProyecto<<Boundary>> {
    - opcCancelar
    - inputNombre
    - inputDescripcion
    - inputEmail
    - opcionCrearProyecto
    + 1. opcionRegistrarNuevoProyecto()
    + 2. abrirVentana()
    + 4. solicitarIngresoDatos()
    + 5. tomarIngresoNombre()
    + 6. tomarIngresoDescripcion()
    + 7. tomarSelecciónRequiereRevisión()
    + 8. tomarOpciónCrearProyecto()
}

class Sesión<<Entity>>{
    - fechaHoraInicio
    - fechaHoraFin
    + 11. getUsuarioLogueado()
}

Proyecto --> "1" Usuario : usuario
PantallaCrearProyecto ..> GestorCrearProyecto
PantallaCrearProyecto <.. GestorCrearProyecto
GestorCrearProyecto ..> Sesión
GestorCrearProyecto..> Proyecto
Sesión --> "1" Usuario : usuario
Proyecto -->"1..*" RolEnProyecto: rolEnProyecto
Rol "1" <-- RolEnProyecto: rol
RolEnProyecto --> "1" Usuario: usuario
@enduml