@startuml CU_Gestion_Tareas
left to right direction
actor :Tiempo: as T
actor :ServidorMail: as ES
actor :Notificador: as N
actor :Tiempo: as T
actor :Usuario: as U

U --> (1. Registrar tarea)
(1. Registrar tarea) <-- "<<extends>>" (36. Modificar tabla de clasificación)
(1. Registrar tarea) <-- "<<extends>>" (35. Crear tabla de clasificación)
U --> (2. Modificar tarea)
(2. Modificar tarea) <-- "<<extends>>" (36. Modificar tabla de clasificación)
(2. Modificar tarea) <-- "<<extends>>" (35. Crear tabla de clasificación)
U --> (3. Eliminar tarea)
U --> (4. Consultar tarea)
U --> (5. Generar y emitir reporte de las tareas\nrealizadas en un lapso de tiempo \n dentro de un proyecto)
(5. Generar y emitir reporte de las tareas\nrealizadas en un lapso de tiempo \n dentro de un proyecto) --> "<<include>>" (38. Consultar tabla de clasificación)
T --> (6. Generar y emitir reporte mensual de las tareas \nrealizadas por un usuario)
(6. Generar y emitir reporte mensual de las tareas \nrealizadas por un usuario) --> N
(6. Generar y emitir reporte mensual de las tareas \nrealizadas por un usuario) --> ES
@enduml

@startuml CU_Gestion_Proyectos
left to right direction
actor :Usuario: as U
actor :ServidorMail: as ES
actor :Notificador: as N

U --> (7. Registrar proyecto)
U --> (8. Modificar proyecto)
U --> (9. Eliminar proyecto)
U --> (10. Consultar proyectos en los que \nparticipa el usuario)
U --> (11. Invitar usuario al proyecto)
(11. Invitar usuario al proyecto) --> "<<include>>" (13. Enviar notificación de \ninvitación a proyecto)
(13. Enviar notificación de \ninvitación a proyecto) --> N
(13. Enviar notificación de \ninvitación a proyecto) --> ES
U --> (14. Aceptar invitación a proyecto)
U --> (15. Rechazar invitación a proyecto)
U --> (16. Eliminar usuario del proyecto)
@enduml

@startuml CU_Administración_Roles
left to right direction
actor :Administrador: as A
A --> (17. Registrar rol)
A --> (18. Modificar rol)
A --> (19. Eliminar rol)
A --> (20. Consultar rol)
@enduml

@startuml CU_Administración_Estado
left to right direction
actor :Administrador: as A
A --> (21. Registrar estado)
A --> (22. Modificar estado)
A --> (23. Eliminar estado)
A --> (24. Consultar estado)
@enduml

@startuml CU_Administración_Prioridad
left to right direction
actor :Administrador: as A
A --> (25. Registrar prioridad)
A --> (26. Modificar prioridad)
A --> (27. Eliminar prioridad)
A --> (28. Consultar prioridad)
@enduml

@startuml CU_Gestion_Usuarios
left to right direction
actor :Administrador: as A
actor :Usuario: as U
U --> (29. Iniciar sesión)
U --> (30. Cerrar sesión)
U --> (31. Recuperar contraseña)
(31. Recuperar contraseña) --> "<<include>>"(32. Enviar mail de recuperación)
A --> (33. Registrar usuario)
A --> (34. Eliminar usuario)
@enduml

@startuml CU_Administración_Tabla_Clasificación
left to right direction
actor :Sistema: as S
S --> (35. Registrar tabla de clasificación)
S --> (36. Modificar tabla de clasificación)
S --> (37. Eliminar tabla de clasificacion)
S --> (38. Consultar tabla de clasificación)
@enduml

@startuml CU_Administración_Amistades
left to right direction
actor :Usuario: as U
U --> (39. Enviar solicitud de amistad)
U --> (40. Eliminar amigo)
U --> (41. Bloquear amigo)
U --> (42. Consultar lista de amigos)
U --> (43. Aceptar solicitud de amistad)
U --> (44. Rechazar solicitud de amistad)
U --> (45. Desbloquear amigo)
@enduml