@startuml MáquinaDeEstadosTarea
hide empty description
[*] --> Pendiente : 1. Registrar tarea() \n registrar()
Pendiente --> Pendiente : 2. Modificar tarea \n [fechaActual <= fechaEntrega] \n atrasar()
Pendiente --> Atrasada : 2. Modificar tarea \n [fechaActual > fechaEntrega] \n atrasar()
Pendiente --> Realizada : 2. Modificar tarea \n [realizada] \n finalizarTarea()
Atrasada --> Eliminada : 2. Modificar tarea \n eliminar()
Atrasada --> RealizadaAtrasada : 2. Modificar tarea \n [realizada] \n finalizarConAtraso()
Eliminada --> [*]
Realizada --> [*]
RealizadaAtrasada --> [*]
@enduml

@startuml DiagramaDeCasosDeUso
left to right direction
actor :Administrador: as A
actor :Usuario: as U
U --> (1. Registrar tarea)
U --> (2. Modificar tarea)
U --> (3. Eliminar tarea)
U --> (4. Consultar tarea)
U --> (5. Generar y emitir reporte de las tareas\nrealizadas en un lapso de tiempo)
U --> (6. Registrar Dashboard)
U --> (7. Modificar Dashboard)
U --> (8. Eliminar Dashboard)
U --> (9. Consultar Dashboard)

A --> (10. Registrar rol)
A --> (11. Modificar rol)
A --> (12. Eliminar rol)
A --> (13. Consultar rol)
A --> (14. Registrar estado)
A --> (15. Modificar estado)
A --> (16. Eliminar estado)
A --> (17. Consultar estado)
A --> (18. Registrar prioridad)
A --> (19. Modificar prioridad)
A --> (20. Eliminar prioridad)
A --> (21. Consultar prioridad)
@enduml

@startuml ModeloDeDominio
left to right direction
hide <<Class>> circle
class Usuario<<Class>>{
    - email
    - nombreUsuario
    - contraseña
    + crear()
    + mostrar()
    + tomarEmail()
    + mostrarEmail()
    + tomarNombreUsuario()
    + mostrarNombreUsuario()
    + tomarContraseña()
    + mostrarContraseña()
}

class Proyecto<<Class>>{
    - nombre
    - descripcion
    - tareas: Tarea
    + crear()
    + mostrar()
}
'aunque crear es por defecto sería el new() o registrar() si le ponemos otro nombre
class Tarea<<Class>>{
    - nombre
    - descripción
    - fechaInicio
    - fechaFin
    - fechaEntrega
    + crear() 
    + mostrar()
    + tomarNombre()
    + mostrarNombre()
    + tomarDescripción()
    + mostrarDescripción()
    + tomarFechaInicio()
    + mostrarFechaInicio()
    + tomarFechaFin()
    + mostrarFechaFin()
    + tomarFechaEntrega()
    + mostrarFechaEntrega()
    + atrasar()
    + finalizar()
    + finalizarConAtraso()
    + eliminar()
}

class EstadoTarea<<Class>>{
    - nombre
    - descripción
    + crear()
    + mostrar()
    + tomarNombre()
    + mostrarNombre()
    + tomarDescripción()
    + mostrarDescripción()
}

class PrioridadTarea<<Class>>{
    - nombre
    - descripción
    + mostrar()
    + tomarNombre()
    + mostrarNombre()
    + tomarDescripción()
    + mostrarDescripción() 
}

Usuario --> "1..*" Proyecto : proyectos
Proyecto --> "1..*" Tarea: tareas
Tarea --> "1" EstadoTarea : estado
Tarea --> "\t\t1" PrioridadTarea :  prioridad
@enduml

@startuml Diagrama Entidad Relacion

entity Tarea{
    id: <<PK>> SERIAL
    titulo: VARCHAR
    descripción: VARCHAR
    fechaInicio: DATE 
    fechaFin: DATE
    fechaEntrega: DATE
    idUsuario: <<FK>>
    idEstadoTarea: <<FK>>
    idPrioridadTarea: <<FK>>
    idProyecto: <<FK>>

}

entity Proyecto{
    id: <<PK>> SERIAL
    nombre: VARCHAR
    descripción: VARCHAR
}

entity PrioridadTarea{
    id: <<PK>> SERIAL
    nombre: VARCHAR
    descripción: VARCHAR
}

entity Usuario{
    id:<<PK>> SERIAL
    email: VARCHAR
    nombre: VARCHAR
    constraseña: VARCHAR
}

entity EstadoTarea{
    id: <<PK>> SERIAL
    descripción: VARCHAR
   
}

entity Proyecto_X_Usuario{
    id: <<PK>> SERIAL
    idProyecto: <<FK>>
    idUsuario: <<FK>>
    idRol: <<FK>>
}

entity Rol{
    id: <<PK>> SERIAL
    nombre: VARCHAR
}

Tarea }|--|| Proyecto
Proyecto ||--|{ Proyecto_X_Usuario
Usuario ||--|{ Proyecto_X_Usuario
Proyecto_X_Usuario }|--|| Rol
Tarea }|--|| EstadoTarea
Tarea }|--|| PrioridadTarea
Tarea }|--|| Usuario

@enduml

@startuml RealizaciónCu1VistaDinámica

skinparam roundcorner 20
skinparam maxmessagesize 60
autonumber

Actor ":__Usuario__" as U
create boundary "__:PantallaRegistrarTarea__" as PCT
U --> PCT : seleccionaOpcionCrearNuevaTarea()
PCT -> PCT : abrirVentana()
create control "__:GestorRegistrarTarea__" as GCT
PCT --> GCT : newRegistrarTarea()
GCT -> PCT : solicitarIngresoDatos()
U -> PCT : tomarIngresoNombre()
U -> PCT : tomarIngresoDescripcion()
PCT  -> GCT : tomarIngresoDatos()
GCT -> PCT : mostrarDatosParaSeleccion()
U -> PCT : tomarSeleccionFechaHoraFin()
'para mí no haría falta validar en este caso que la fecha sea mayor a la actual
' ya que se lo limitamos al hacer la selección. Podemos ver bien despues eso
U -> PCT : tomarSeleccionPrioridad()
PCT -> GCT : tomarSeleccionDatos()
GCT -> GCT : verificarDatosMinimos()
GCT -> GCT : crearTarea()
GCT -> GCT : getFechaHoraActual()
GCT -> GCT : buscarEstadoPendiente()
loop Buscar estado Pendiente
    entity "__:EstadoTarea__" as E #LightCoral
else Mientras existan estados
    GCT -> E : sosPendiente()
end
create entity "__nueva:Tarea__" as T
GCT --> T : registrar()
GCT -> GCT : finCU()

@enduml
@startuml RealizaciónCu1VistaEstática
left to right direction
hide <<Class>> circle
class Usuario<<Class>>{
    - email
    - nombreUsuario
    - contraseña
    + crear()
    + mostrar()
    + tomarEmail()
    + mostrarEmail()
    + tomarNombreUsuario()
    + mostrarNombreUsuario()
    + tomarContraseña()
    + mostrarContraseña()
}

class Proyecto<<Class>>{
    - nombre
    - descripcion
    - tareas: Tarea
    + crear()
    + mostrar()
}

class Tarea<<Class>>{
    - nombre
    - descripción
    - fechaInicio
    - fechaFin
    - fechaEntrega
    + crear()
    + mostrar()
    + tomarNombre()
    + mostrarNombre()
    + tomarDescripción()
    + mostrarDescripción()
    + tomarFechaInicio()
    + mostrarFechaInicio()
    + tomarFechaFin()
    + mostrarFechaFin()
    + tomarFechaEntrega()
    + mostrarFechaEntrega()
    + atrasar()
    + finalizar()
    + finalizarConAtraso()
    + eliminar()
}

class EstadoTarea<<Class>>{
    - nombre
    - descripción
    + crear()
    + mostrar()
    + tomarNombre()
    + mostrarNombre()
    + tomarDescripción()
    + mostrarDescripción()
}

class PrioridadTarea<<Class>>{
    - nombre
    - descripción
    + mostrar()
    + tomarNombre()
    + mostrarNombre()
    + tomarDescripción()
    + mostrarDescripción() 
}
class GestorCrearTarea <<control>> {
    - fechaHoraActual
    - estadoPendiente
    - nombreTarea
    - descripcionTarea
    - fechaHoraFinTarea
    - prioridadTarea
    + newCrearTarea()
    + tomarIngresoDatos()
    + tomarSeleccionDatos()
    + verificarDatosMinimos()
    + crearTarea()
    + getFechaHoraActual()
    + buscarEstadoPendiente()
}
class PantallaCrearTarea <<boundary>> {
    - opcCancelar
    - opcAceptar
    - inputNombre
    - inputDescripcion
    'No se qué tipo va en prioridad y en fechaHoraFin
    + abrirVentana()
    + solicitarIngresoDatos()
    + tomarIngresoNombre()
    + tomarIngresoDescripcion()
    + mostrarDatosParaSeleccion()
    + tomarSeleccionFechaHoraFin()
    + tomarSeleccionPrioridad()
    + finCU()
}
Usuario --> "1..*" Proyecto : proyectos
Proyecto --> "1..*" Tarea: tareas
Tarea --> "1" EstadoTarea : estado
Tarea --> "\t\t1" PrioridadTarea :  prioridad
PantallaCrearTarea ..> GestorCrearTarea
PantallaCrearTarea <.. GestorCrearTarea
Tarea <.. GestorCrearTarea
EstadoTarea <.. GestorCrearTarea
@enduml