@startuml MáquinaDeEstadosTarea
left to right direction
hide empty description
[*] --> Pendiente : 1. Registrar tarea \n registrar()
Pendiente --> Realizada : 2. Modificar tarea \n finalizar()
Pendiente --> Haciendo: 2. Modificar tarea \n hacer()
Pendiente --> EnRevision: 2. Modificar tarea \n revisar()
Pendiente --> Eliminada: 2. Modificar tarea \n eliminar()

Haciendo --> Realizada: 2. Modificar tarea \n finalizar()
Haciendo --> EnRevision: 2. Modificar tarea \n revisar()
Haciendo --> Pendiente: 2. Modificar tarea \n ponerEnPendiente()
Haciendo --> Eliminada: 2. Modificar tarea \n eliminar()

EnRevision --> Realizada: 2. Modificar tarea \n finalizar()
EnRevision --> Pendiente: 2. Modificar tarea \n ponerEnPendiente()
EnRevision --> Haciendo: 2. Modificar tarea \n hacer()
EnRevision --> Eliminada: 2. Modificar tarea \n eliminar()

Realizada --> EnRevision: 2. Modificar tarea \n finalizar()
Realizada --> Haciendo: 2. Modificar tarea \n hacer()
Realizada --> Pendiente : 2. Modificar tarea \n ponerEnPendiente()
Realizada --> Archivada: 2. Modificar tarea \n archivar()

Archivada --> Eliminada: 2. Modificar tarea \n eliminar()
Archivada --> Realizada: 2. Modificar tarea \n finalizar()

Eliminada --> [*]
@enduml

@startuml MáquinaDeEstadosInvitación
left to right direction
hide empty description
[*] --> Pendiente : 11. Invitar usuario al proyecto \n invitarUsuario()

Pendiente --> Aceptada : 14. Aceptar invitación a proyecto \n aceptarInvitación()
Pendiente --> Pendiente : 15. Rechazar invitación a proyecto \n [fechaExpiración >= fechaActual] \n rechazarInvitación()
Pendiente --> Eliminada : 15. Rechazar invitación a proyecto \n rechazarInvitación()

Aceptada --> [*]
Eliminada --> [*]
@enduml